### ISSUE TITLE
Terminal settings for Versa 2 only shows username field

### ISSUE THREAD

**Issue by ChrisAkridge** [jdhartley/terminal-for-fitbit#11]
Fitbit Versa 2 version 35.68.9.15

![Screenshot](https://i.imgur.com/R86MozF.png)

**Comment by jdhartley** [comment]
Hey @ChrisAkridge! Thanks for opening this bug report

I see that your Fitbit firmware version is 35.68.9.15; this appears to be a few versions old, and you may need to upgrade your Fitbit device OS to see the latest version of Terminal.

Can you try upgrading your firmware version? Check out [How do I update my Fitbit device?](https://help.fitbit.com/articles/en_US/Help_article/1871.htm) for more details

**Comment by ChrisAkridge** [comment]
Thanks @jdhartley! I'll look in to updating my firmware.
