### ISSUE TITLE
[bug] user@versa:~ $no

### ISSUE THREAD

**Issue by sczze** [jdhartley/terminal-for-fitbit#14]
Instead of saying now it shows no.
I have already tried reinstalling. It showed 'now'. But once I on the watch a while later the same problem happened again
Pls advice thank you.[
![IMG_20200920_161107](https://user-images.githubusercontent.com/66111820/93706773-5df32400-fb5c-11ea-9804-665c577953e1.jpg)
](url)

**Comment by jdhartley** [comment]
Thanks for this bug report, I can confirm this is broken. I will need to extend the character count of that row and submit a new build to fitbit. I will try to get this done in the next day or two!!! Will keep you up to date

**Comment by jdhartley** [comment]
Hi @sczze, I have just submitted v2.0.2 to Fitbit for review. I will leave this issue open until it is approved and ready for download! Thanks again for reporting this issue

**Comment by jdhartley** [comment]
Hello @sczze, you should now be able to upgrade to v2.0.2 via the Fitbit app!
