### ISSUE TITLE
[Idea] Cursor flashing at last row

### ISSUE THREAD

**Issue by seemebreakthis** [jdhartley/terminal-for-fitbit#17]
Perfect watchface but what if there is a flashing underscore cursor to make it look even more realistic?

I would be all for this option even if that means a little bit of scraifice on battery usage !

Thanks for considering.

**Comment by jdhartley** [comment]
Hi @seemebreakthis, thanks for the feature idea! This sounds like a fun feature. I believe I can make this happen, and support multiple cursor styles as well. I will mark as a v2.2 feature!

**Comment by jdhartley** [comment]
Hey @seemebreakthis, I started on this feature tonight! It's a great candidate for me to do some internal clean up to support sdk 4 and 5 in one branch.

I wanted to ask if you have a preferred caret/cursor style. I am planning to support multiple styles.

My current list is:

- none / off
- block
- underscore
- vertical pipe

In your original post you mentioned an underscore, but I am curious if your preference is in that list!

**Comment by seemebreakthis** [comment]
Hello @jdhartley, thank you so so much for responding to this !  Frankly I don't really mind which one, but of these options if they are all available, I will likely be changing around but mostly sticking with underscore flashing (and/or underscore solid).  Flashing will look even more awesome I think so I will probably stick with that most of the time.

Really looking forward to the change !!  Cheers mate.

**Comment by jdhartley** [comment]
Thanks again for this feature suggestion! I have just submitted it for review. I know it has been years since you opened this issue, but if you still use a fitbit and this clock face, I hope you enjoy!

**Comment by seemebreakthis** [comment]
Thanks forfinally adding it.  But too bad I no longer use Fitbit.  (Do you do development on Garmin Venu 2 as well...?  :) )
