### ISSUE TITLE
Custom heartrate ranges do not display status properly

### ISSUE THREAD

**Issue by VJohnston13** [jdhartley/terminal-for-fitbit#19]
In your images I see either the bpm or the bpm and workout detected. So what is "below-cus"?

Also the battery has [############] before the %. This is shown, but I'm just wondering why it's there.

I will edit this with a pic of my versa screen when I get a chance.

**Comment by jdhartley** [comment]
Hey @VJohnston13 thanks for opening this up -- hoping I can clarify and maybe fix some bugs :bug: 

I think "below-cus" is likely "below custom zone". I hadn't thought of testing that, so I may need to tweak something here. Can you confirm you have custom heart rate zones set up?

The `[############]` is a battery bar that will decrease over time, for example: ` [########....] 61%` is what shows on my device right now

**Comment by jdhartley** [comment]
Great, thanks for confirming this for me! I will look into this more, I will use this issue to keep track of this!

**Comment by jdhartley** [comment]
> When the user has configured a custom zone, the possible values are, in order of increasing heart rate:
>
> - "below-custom" when the heart rate is below the custom zone.
> - "custom" when the heart rate is in the custom zone.
> - "above-custom" when the heart rate is above the custom zone.

https://dev.fitbit.com/build/reference/device-api/user-profile/

We have 8 characters to display a heart rate status.

I think `below-custom` can be ignored (same as `out-of-range`)
`custom` can say `XXX bpm in zone`
`above-custom` can go to `XXX bpm gt zone` or `> zone` maybe?

If anyone has ideas for "above custom zone range" in 8 chars ... I am all ears!!!
