### ISSUE TITLE
[Feature Request] Active Zone Minutes AZM 

### ISSUE THREAD

**Issue by kmf** [jdhartley/terminal-for-fitbit#22]
I would love to see Active Zone Minutes

**Comment by LeoneKayla-FS** [comment]
I came here to request the same. I LOVE this watch face and active zone minutes is the main thing alongside steps that I keep an eye on.

**Comment by jdhartley** [comment]
Thanks everyone! this is possible now using SDK 4.2, and I should be able to add it to the watch face soon. I had put off a bunch of updates waiting for new features from Fitbit, and I think it's about time to knock these out! Thanks for your patience and support :pray:

**Comment by kmf** [comment]
Thanks. My fitbit died last week 😭
