### ISSUE TITLE
Cursor Floating in Limbo

### ISSUE THREAD

**Issue by end-user-jutsu** [jdhartley/terminal-for-fitbit#39]
If the user has deselected a number of elements (or "clock face data") the cursor will still hang out blinking in the bottom-right corner, regardless how far away the remaining elements sit on the screen. 

Ps. Great clock face, thanks! 🥂

**Comment by jdhartley** [comment]
Thanks for the bug report! 🤦‍♂️ of course I missed this! I believe this will be a fairly easy fix and will work to get it submitted to Fitbit's review team in the coming day or two.

PS, Appreciate the kind words! 🚀
