### ISSUE TITLE
[Feature Request] 24hr Clock

### ISSUE THREAD

**Issue by Creaden37** [jdhartley/terminal-for-fitbit#46]

**Comment by jdhartley** [comment]
Hi @Creaden37, thanks for this feature request!

Right now the [code does respond to your profile settings](https://github.com/jdhartley/terminal-for-fitbit/blob/sdk5/app/datalines/time.js#L16L21) and switches to 24 hours automatically

You can find the steps to do so via this Fitbit help doc: [How do I change to a 12 or 24 hour clock?](https://help.fitbit.com/articles/en_US/Help_article/1176.htm)

Does this work for your needs? Let me know!

**Comment by Creaden37** [comment]
That did work, thanks for that info.
