### ISSUE TITLE
Terminal Clock on Fitbit Ionic 

### ISSUE THREAD

**Issue by CyberSecStudent2022** [jdhartley/terminal-for-fitbit#47]
Hello, I’m wondering if you might have a suggestion on what I can do to get the Terminal Clock to work on my Fitbit Ionic. I’ve tried un-installing and re-installing the app itself as was suggested when troubleshooting as well as removing the terminal clock and reinstalling it. I’ve tried setting it as my clock in the settings on the app as well as on the Fitbit itself and it vibrates like it registers the change of clock face but the background just goes black and won’t show anything until reverting back to the original clock in the settings of the app. This happens wether the terminal is set to dark mode or light mode, background is still black/blank.

**Comment by jdhartley** [comment]
Hi there, thank you for reporting

I have discovered a bug in the Ionic version of the latest v2.3.0-legacy. I am working to push a bugfix, which you can sideload, or wait for it to make it to the fitbit store

In the meantime, you can sideload the [v2.0.2 app.fba](https://github.com/jdhartley/terminal-for-fitbit/releases/tag/2.0.2) — my guess is it might be about a week for Fitbit to approve and release the updated version once I submit given the holiday

Thanks for reporting! I'll keep you posted on developments 👍

**Comment by jdhartley** [comment]
This was quick! I have pushed up the fix at [tag v2.3.1-legacy](https://github.com/jdhartley/terminal-for-fitbit/releases/tag/2.3.1-legacy) and have submitted to Fitbit for review. Thanks for your patience and hope you enjoy using the clock face!

**Comment by jdhartley** [comment]
This has been published as `v2.3.1a-legacy` to the fitbit app gallery! You should be able to pull the upgrade and use the clockface now! Thanks for reporting this bug
