### ISSUE TITLE
Allow changing $ to # for extra leetness

### ISSUE THREAD

**Issue by qpfox** [jdhartley/terminal-for-fitbit#51]
Just discovered this awesome face, and it would be even more awesome with an option for a superuser style prompt!

**Comment by jdhartley** [comment]
Ha! I love it — I am down to add a "Sudo mode" (or "Superuser mode" if you think its better)

**Comment by qpfox** [comment]
I'd go with either "superuser mode" or "leet mode" if it were up to me!

**Comment by jdhartley** [comment]
This was pretty quick and fun to toss together! I plan to build and submit sometime this week if not later tonight

![image](https://user-images.githubusercontent.com/405538/219225804-941bf196-da44-4ba8-b242-b0d5e573c8f0.png)
![image](https://user-images.githubusercontent.com/405538/219225832-997e7c5a-569e-418b-ba97-13aa2ef0a6aa.png)
