### ISSUE TITLE
[Feature request] Ability to show distance on Sense

### ISSUE THREAD

**Issue by AdnanHodzic** [jdhartley/terminal-for-fitbit#54]
First of all, I don't think I was ever this excited about a Fitbit clock face, so kudos for great work! :slightly_smiling_face: 

The only thing I miss is ability to see distance `[DIST]`, as [this is what it looks like on my Sense](https://twitter.com/fooctrl/status/1639922547943964677).

Hence, could it possible to to add it to the clock face? As an alternative, in case if there isn't enough space to add another row, would it be possible to have ability to replace `[STEP]` or `[BATT]` with `[DIST]`.

Thanks!

**Comment by jdhartley** [comment]
Hi Adnan! I'm so glad you are enjoying the clock face!

If you enter your phones Fitbit app and find your way to the clock face settings, you'll find a ton of configuration waiting, including a DIST row. You can add/remove/reorder data lines, change the username, switch color themes and fonts, and more. I hope you find the perfect setup!

Let me know if you run into any issues, happy to help
