### ISSUE TITLE
[feature suggest] Add support for displaying calories

### ISSUE THREAD

**Issue by xantho** [jdhartley/terminal-for-fitbit#7]
I would love to see my calories on the watch face.

**Comment by jdhartley** [comment]
Thanks for the feature suggestion @xantho!

Do you have a suggestion on how to format the information? I would love to hear your ideal display.

Perhaps something like,

```
[KCAL] 100 Cal (5%)
[KCAL] 2500 Cal (125%)
```

**Comment by xantho** [comment]
Mmh... I thought the units (same with "steps") are not needed when the initial [...] is chosen right. But I really like the percentage display. So maybe something like:

[CALS] 100 (5%)
[CALS] 2500 (125%)

That's kind of what the tracker displays right now in the daily activity feed. Maybe the percentage and the lack of displaying unnecessary units would look good on the other display lines as well.

**Comment by exolon** [comment]
I discovered the face last night and came here to request the same since it's a really nice watchface but cals are kind of basic!

For me a mix of the two proposals would be the best:
[KCAL] 3000 (100%)

No need to repeat the unit, but at the same time the unit is **K**cal, not simply Cal.

**Comment by xantho** [comment]
If you look at the Fitbit "Today" interface there is only the description "calories" so ```[CALS]``` is not entirely wrong. On the other side it would be ok for me to see a row like you suggested because you are right it is essentially ```[KCAL]```.

**Comment by exolon** [comment]
You are right, and Fitbit is, of course, wrong :D

**Comment by jdhartley** [comment]
It's my understanding that 1 kilocalorie/kcal === 1 Calorie (upper C) === 1000 calories (lower c)

So we could do any of these:

1. `[KCAL] 1000 kcal (43%)`
1. `[CALS] 1000 Cal (43%)`
1. some mix of `KCAL`/`CALS` + `kcal`/`Cal`

My preference would be on 2. above, it matches Fitbit's vernacular

**Comment by xantho** [comment]
I agree. Second one is pretty good.

**Comment by exolon** [comment]
> It's my understanding that 1 kilocalorie/kcal === 1 Calorie (upper C) === 1000 calories (lower c)

Last night I saw your comment and I was going to reply that "I never saw a measurement unit changing its initial to denote 1000! Are you nuts?" :D 

But then I seemed to recall something - indeed there's the large or big Calorie or whatever they call it, which is kcal indeed. It's stupid, but not as stupid as it seems at first - it's actually a different unit definition; whereas cal is energy/ml, Cal is energy/l, so it's x1000, ergo kcal...

That said, #2 looks pretty cool :D

**Comment by Smorsken** [comment]
Just jumping in with my opinion. Great clock face, thank you so much! #2 is good! Really want this feature \[^_^]/

**Comment by thepedroferrari** [comment]
Heya, just came to ask for this feature as well!
The format proposed sounds great to me.
Cheers

**Comment by nayfield** [comment]
Upvote

**Comment by ma-lacroix** [comment]
Also upvote!

**Comment by arellatoga** [comment]
upvoting this request. would love to see my cals!
