### ISSUE TITLE
[feature suggest] Add support for displaying active minutes

### ISSUE THREAD

**Issue by xantho** [jdhartley/terminal-for-fitbit#8]
I would love to see my daily active minutes directly on the watch face.

**Comment by jdhartley** [comment]
Thanks for the feature suggestion @xantho!

Do you have a suggestion on how to format the information? I would love to hear your ideal display.

My first thought is something like,

```
[MOVE] 23 min (38%)
```

Unsure if `[MOVE]` is the right label, definitely open to ideas!

**Comment by xantho** [comment]
Mmh... That's kind of hard...

[ACTM] 23min (38%)

Maybe that's more clear than [MOVE] ? Hard to decide... Otherwise I like the choice!

**Comment by jdhartley** [comment]
Also dropping in `[AZMS]` here, I think this would be a nice addition alongside this feature
https://dev.fitbit.com/blog/2020-09-10-announcing-fitbit-os-sdk-4.2/

With the new devices and some recent API updates, I plan to spend some time on this project again very soon.

**Comment by xantho** [comment]
I didn't notice Fitbit changing that. Yeah, sounds good!
