### ISSUE TITLE
Cannot add line unless all are removed

### ISSUE THREAD

**Issue by exolon** [jdhartley/terminal-for-fitbit#9]
In the app settings, if I remove a line, there's no way to add one. I have to remove ALL the lines before the "Add" option appears that lets me do so.

Minor bug, to be sure.

**Comment by jdhartley** [comment]
Hi @exolon, thanks for the bug report! I appreciate your time and am glad you are enjoying the clock face

I believe that you are seeing the "Add Action" button disappear during Edit mode. Here's my assumption:

1. You open settings, scroll to "Clock face data"
2. You see "All rows are full"
3. You press "Edit"
4. You remove a row
5. EXPECTED: See "Add Item" button; ACTUAL: no button :cry: 

**Here's the workaround:
If you press "Done", the rearrange/remove UI should close and the "Add Item" button should appear.**

Let me know if my assumed reproduction steps/workaround are wrong, or you are not seeing this behavior on your device!

---

I did some brief research into this... I would like to improve this UX if possible

It looks like the `<AdditiveList>` component provided by Fitbit hides the `addAction` component while it is in Edit mode. [Here's the code that is generating this UI](https://github.com/jdhartley/terminal-for-fitbit/blob/3636bd8a25aa10302b3b622b9767037c13960e68/settings/index.jsx#L53-L60)

My first thought was adding a help message under the list during edit mode, but I don't see a way for me to detect the Edit mode starting/ending... sadly these components are pretty bare-bones.

I am open to ideas/suggestions here! Thanks again for your time

**Comment by exolon** [comment]
Good morning!

Yes, your assumptions were correct, that's the flow, and indeed the workaround works nicely.

It's not a biggie, one figures it out pretty quickly to be honest. But you could add the text anyhow, no need for it to be conditional on whether Edit mode is active or not - just put it under the section :)

**Comment by jdhartley** [comment]
Thanks for filing this bug report @exolon! This has been addressed in the just-released v2.0.1, now available in the Fitbit app.

**Comment by exolon** [comment]
Cheers, will check it out once the Gallery is up (hasn't been working for me since yesterday)!!
